development:
  adapter: postgresql
  port:     5432
  schema_search_path: public
  min_messages: warning
  database: ffcrm_development
  username: postgres
  password: postgres
  host:     localhost

production:
  adapter: postgresql
  port:     5432
  schema_search_path: public
  min_messages: warning
  database: ffcrm_production
  username: postgres
  password: f98g7w4c87wj984tyow846h984x7
  host:     fat-free-crm.caw9il2l1fjn.us-east-1.rds.amazonaws.com